"use client";

import { useEffect, useRef, useState } from "react";
import { useGameStore } from "@/lib/game-store";
import { BACKGROUNDS, BACKGROUND_MAPPING } from "@/lib/constants";
import { cn } from "@/lib/utils";

interface GameCanvasProps {
  className?: string;
}

// Game Boy 4-color palette
const GB = {
  BLACK: "#0f380f",
  DARK: "#306230",
  LIGHT: "#8bac0f",
  WHITE: "#9bbc0f",
};

// Sprite pixel art data - using numbers 0-3 for the 4 GB colors
// 0=BLACK, 1=DARK, 2=LIGHT, 3=WHITE, .=transparent
const SPRITES: Record<string, string> = {
  male_young: `
........000.........
.......03330........
......0333330.......
.....033333330......
.....033030330......
.....033333330......
......0333330.......
.......03330........
........000.........
.......01110........
......0111110.......
.....011111110......
.....011111110......
......0111110.......
.......01110........
........010.........
.......01110........
......011.110.......
.....011...110......
.....01.....10......`,
  female_young: `
........000.........
.......03330........
......0333330.......
.....033333330......
....03333333330.....
....03330303330.....
....03333333330.....
.....033333330......
......0333330.......
.......03330........
........000.........
.......02220........
......0222220.......
.....022222220......
.....022222220......
......0222220.......
.......02220........
........020.........
.......02220........
......022.220.......
.....022...220......
.....02.....20......`,
  male_adult: `
.......0000.........
......033330........
.....03333330.......
....0333333330......
....0333030330......
....0333333330......
.....03333330.......
......033330........
.......0000.........
......011110........
.....01111110.......
....0111111110......
....0111111110......
....0111111110......
.....01111110.......
......011110........
.......0110.........
......011110........
.....011..110.......
....011....110......
....01......10......
...01........10.....`,
  female_adult: `
.......0000.........
......033330........
.....03333330.......
....0333333330......
...033333333330.....
...033303033330.....
...033333333330.....
....0333333330......
.....03333330.......
......033330........
.......0000.........
......022220........
.....02222220.......
....0222222220......
....0222222220......
....0222222220......
.....02222220.......
......022220........
.......0220.........
......022220........
.....022..220.......
....022....220......
....02......20......`,
  male_old: `
.......0000.........
......022220........
.....02222220.......
....0222222220......
....0222020220......
....0222222220......
.....02222220.......
......022220........
.......0220.........
......011110........
.....01111110.......
....0111111110......
....0111111110......
....0111111110......
.....01111110.......
......011110........
.......0110.........
......011110........
.....011..110.......
....011....110......
....01......10......
...01........10.....`,
  female_old: `
.......0000.........
......022220........
.....02222220.......
....0222222220......
...022222222220.....
...022202022220.....
...022222222220.....
....0222222220......
.....02222220.......
......022220........
.......0000.........
......022220........
.....02222220.......
....0222222220......
....0222222220......
....0222222220......
.....02222220.......
......022220........
.......0220.........
......022220........
.....022..220.......
....022....220......
....02......20......`,
};

export function GameCanvas({ className }: GameCanvasProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const [isLoaded, setIsLoaded] = useState(false);
  const [currentBg, setCurrentBg] = useState<string>("nursery");
  const [dimensions, setDimensions] = useState({ width: 960, height: 540 });

  const age = useGameStore((state) => state.age);
  const gender = useGameStore((state) => state.gender);
  const location = useGameStore((state) => state.currentTurn?.location);
  const isDead = useGameStore((state) => state.gameState === "dead");

  // Load and cache background images
  const imagesRef = useRef<Map<string, HTMLImageElement>>(new Map());

  // Handle resize
  useEffect(() => {
    const updateSize = () => {
      if (containerRef.current) {
        const rect = containerRef.current.getBoundingClientRect();
        setDimensions({ 
          width: Math.max(480, rect.width), 
          height: Math.max(320, rect.height) 
        });
      }
    };
    updateSize();
    window.addEventListener("resize", updateSize);
    return () => window.removeEventListener("resize", updateSize);
  }, []);

  useEffect(() => {
    const loadImages = async () => {
      const loadPromises = Object.entries(BACKGROUNDS).map(([key, path]) => {
        return new Promise<void>((resolve) => {
          const img = new Image();
          img.crossOrigin = "anonymous";
          img.onload = () => {
            imagesRef.current.set(key, img);
            resolve();
          };
          img.onerror = () => resolve();
          img.src = path;
        });
      });
      await Promise.all(loadPromises);
      setIsLoaded(true);
    };
    loadImages();
  }, []);

  // Determine background based on location or age
  useEffect(() => {
    let targetBg = "park";
    if (location) {
      const lowerLocation = location.toLowerCase();
      for (const [keywords, bg] of Object.entries(BACKGROUND_MAPPING)) {
        const keywordList = keywords.split(",");
        if (keywordList.some((kw) => lowerLocation.includes(kw.trim()))) {
          targetBg = bg;
          break;
        }
      }
    } else {
      if (age <= 4) targetBg = "nursery";
      else if (age <= 12) targetBg = "classroom";
      else if (age <= 18) targetBg = "bedroom";
      else if (age <= 25) targetBg = "dorm";
      else if (age <= 60) targetBg = "office";
      else targetBg = "nice_home";
    }
    if (targetBg !== currentBg) {
      setCurrentBg(targetBg);
    }
  }, [location, age, currentBg]);

  // Draw the canvas with background AND sprite
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas || !isLoaded) return;

    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    const W = dimensions.width;
    const H = dimensions.height;

    // Clear canvas
    ctx.fillStyle = GB.WHITE;
    ctx.fillRect(0, 0, W, H);

    // Draw background image
    const bgImage = imagesRef.current.get(currentBg);
    if (bgImage) {
      const scale = Math.max(W / bgImage.width, H / bgImage.height);
      const x = (W - bgImage.width * scale) / 2;
      const y = (H - bgImage.height * scale) / 2;
      ctx.drawImage(bgImage, x, y, bgImage.width * scale, bgImage.height * scale);
    }

    // Draw character sprite ON the canvas (integrated into scene)
    if (!isDead) {
      drawCharacterSprite(ctx, W, H, age, gender || "male");
    }

    // If dead, draw graveyard overlay
    if (isDead) {
      drawDeathOverlay(ctx, W, H);
    }
  }, [isLoaded, currentBg, dimensions, age, gender, isDead]);

  return (
    <div ref={containerRef} className={cn("relative w-full h-full overflow-hidden", className)}>
      <canvas
        ref={canvasRef}
        width={dimensions.width}
        height={dimensions.height}
        className="w-full h-full"
        style={{ imageRendering: "pixelated" }}
      />

      {/* Top gradient for HUD readability */}
      <div 
        className="absolute top-0 inset-x-0 h-12 pointer-events-none"
        style={{ background: 'linear-gradient(180deg, rgba(15, 56, 15, 0.6) 0%, transparent 100%)' }}
      />

      {/* Bottom gradient for dialogue readability */}
      <div 
        className="absolute bottom-0 inset-x-0 h-16 pointer-events-none"
        style={{ background: 'linear-gradient(0deg, rgba(15, 56, 15, 0.7) 0%, transparent 100%)' }}
      />

      {/* Loading state */}
      {!isLoaded && (
        <div className="absolute inset-0 flex items-center justify-center bg-gb-darkest">
          <p className="font-pixel text-xs text-gb-light animate-pulse">Loading...</p>
        </div>
      )}
    </div>
  );
}

function drawCharacterSprite(
  ctx: CanvasRenderingContext2D,
  W: number,
  H: number,
  age: number,
  gender: string
) {
  // Determine age group
  let ageGroup = "young";
  if (age > 55) ageGroup = "old";
  else if (age > 12) ageGroup = "adult";

  const spriteKey = `${gender}_${ageGroup}`;
  const spriteData = SPRITES[spriteKey] || SPRITES.male_young;

  // Calculate sprite scale based on canvas size
  const baseScale = Math.max(4, Math.floor(W / 160));
  const spriteScale = ageGroup === "young" ? baseScale : baseScale + 1;

  // Position sprite on the left side, standing on the "floor" at ~64% height
  const spriteX = Math.floor(W * 0.10);
  const lines = spriteData.trim().split("\n");
  const spriteH = lines.length * spriteScale;
  const floorY = Math.floor(H * 0.68);
  const spriteY = floorY - spriteH;

  // Color map for sprite pixels
  const colorMap: Record<string, string> = {
    "0": GB.BLACK,
    "1": GB.DARK,
    "2": GB.LIGHT,
    "3": GB.WHITE,
  };

  // Draw each pixel of the sprite
  lines.forEach((line, y) => {
    for (let x = 0; x < line.length; x++) {
      const char = line[x];
      if (char !== "." && colorMap[char]) {
        ctx.fillStyle = colorMap[char];
        ctx.fillRect(
          spriteX + x * spriteScale,
          spriteY + y * spriteScale,
          spriteScale,
          spriteScale
        );
      }
    }
  });
}

function drawDeathOverlay(ctx: CanvasRenderingContext2D, W: number, H: number) {
  // Darken the background
  ctx.fillStyle = "rgba(15, 56, 15, 0.85)";
  ctx.fillRect(0, 0, W, H);

  const cx = Math.floor(W / 2);
  const groundY = Math.floor(H * 0.62);
  const s = Math.max(3, Math.floor(W / 200));

  // Ground
  ctx.fillStyle = GB.DARK;
  ctx.fillRect(0, groundY, W, H - groundY);
  ctx.fillStyle = GB.LIGHT;
  ctx.fillRect(0, groundY, W, s);

  // Central gravestone
  const stoneW = s * 14;
  const stoneH = s * 22;
  const stoneX = cx - stoneW / 2;
  const stoneY = groundY - stoneH;

  ctx.fillStyle = GB.DARK;
  ctx.fillRect(stoneX, stoneY + s * 4, stoneW, stoneH - s * 4);
  ctx.fillRect(stoneX + s * 2, stoneY, stoneW - s * 4, s * 4);
  ctx.fillRect(stoneX + s, stoneY + s, stoneW - s * 2, s * 3);

  ctx.fillStyle = GB.LIGHT;
  ctx.fillRect(stoneX + s * 2, stoneY + s * 3, stoneW - s * 4, stoneH - s * 6);

  // Cross on stone
  ctx.fillStyle = GB.DARK;
  const crossCy = stoneY + s * 9;
  ctx.fillRect(cx - s, crossCy - s * 5, s * 2, s * 10);
  ctx.fillRect(cx - s * 4, crossCy - s * 2, s * 8, s * 2);

  // Small crosses on sides
  ctx.fillStyle = "rgba(139, 172, 15, 0.5)";
  // Left cross
  ctx.fillRect(cx - s * 25, groundY - s * 12, s * 2, s * 8);
  ctx.fillRect(cx - s * 28, groundY - s * 9, s * 8, s * 2);
  // Right cross
  ctx.fillRect(cx + s * 23, groundY - s * 14, s * 2, s * 8);
  ctx.fillRect(cx + s * 20, groundY - s * 11, s * 8, s * 2);

  // Coffin
  const coffinW = s * 20;
  const coffinH = s * 6;
  const coffinX = cx - coffinW / 2;
  const coffinY = groundY + s * 3;

  ctx.fillStyle = GB.BLACK;
  ctx.fillRect(coffinX + s * 2, coffinY, coffinW - s * 4, coffinH);
  ctx.fillRect(coffinX, coffinY + s, coffinW, coffinH - s * 2);

  ctx.fillStyle = GB.DARK;
  ctx.fillRect(coffinX + s * 3, coffinY + s, coffinW - s * 6, s);

  // Cross on coffin
  ctx.fillStyle = "rgba(139, 172, 15, 0.6)";
  ctx.fillRect(cx - s, coffinY + s, s * 2, coffinH - s * 2);
  ctx.fillRect(cx - s * 3, coffinY + s * 2, s * 6, s);
}
